version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: udoy2/imagetextify_s:1.0.3  # Tagging the image
    container_name: imagetextify_c
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      # might add environment variables if needed
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
