version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: udoy2/ocr_server:latest  # Tagging the image
    container_name: fastapi-container
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      # might add environment variables if needed
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
